# Objective :- 


* We will predict for weather the person is having diabetes or not.

* 1 = Yes and 0 = No

# Step 1 :Library & Data Import

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import os
import numpy as np
import pandas as pd
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [4]:
data = pd.read_csv(r'C:\Users\admin\Desktop\Machine Learning\KNN\Problem 2\diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

#  Step 2 : Data Pre-Processing

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               767 non-null    int64  
 1   Glucose                   767 non-null    int64  
 2   BloodPressure             767 non-null    int64  
 3   SkinThickness             767 non-null    int64  
 4   Insulin                   767 non-null    int64  
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64  
 8   Outcome                   767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


### Removing irrelevant  

In [6]:
data['Outcome'].replace(0, 'No', inplace = True)
data['Outcome'].replace(1, 'Yes', inplace = True)

In [7]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age Outcome  
0                     0.627   50     Yes  
1                     0.351   31      No  
2                     0.672   32     Yes  
3                     0.167   21      No  
4                     2.288   33     Yes

### Bad Rate Analysis 

In [8]:
data.Outcome.value_counts()

No     499
Yes    268
Name: Outcome, dtype: int64

# Step 3 : Data Partition

In [9]:
#Dividing data into train and test dataset
from sklearn.model_selection import train_test_split
#from random import seed

#seed(20)
train_x = data.drop(['Outcome'],axis=1)
train_y = data['Outcome']

# Train test split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.3,random_state=20)

In [10]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
620            2      112             86             42      160  38.4   
521            3      124             80             33      130  33.2   
685            2      129             74             26      205  33.2   
3              1       89             66             23       94  28.1   
74             1       79             75             30        0  32.0   

     DiabetesPedigreeFunction  Age  
620                     0.246   28  
521                     0.305   26  
685                     0.591   25  
3                       0.167   21  
74                      0.396   22

#  Step 4 : Scaling Data

In [11]:
from sklearn.preprocessing import StandardScaler ,minmax_scale
scaler = StandardScaler()   # converting data into Z-scale = X-mean / Standard Deviation
#scaler.fit(X_train)         # Mean = 0 & standard Deviation =1

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train[0:5]

array([[-0.57183458, -0.28101982,  0.93999815,  1.36822396,  0.67103592,
         0.86555081, -0.68327306, -0.46186163],
       [-0.27309839,  0.09320782,  0.60328239,  0.79986846,  0.4129637 ,
         0.18600285, -0.50411111, -0.63032563],
       [-0.57183458,  0.249136  ,  0.26656664,  0.35781419,  1.05814425,
         0.18600285,  0.36436886, -0.71455762],
       [-0.87057077, -0.99828945, -0.1823877 ,  0.16836236,  0.10327704,
        -0.48047689, -0.92316787, -1.05148561],
       [-0.87057077, -1.31014581,  0.32268593,  0.61041663, -0.70534926,
         0.02918409, -0.22777657, -0.96725361]])

In [13]:
X_train.mean(axis=0)

array([ 1.06051155e-16,  1.32563943e-16, -4.14262323e-18, -1.98845915e-17,
       -6.62819716e-17, -9.41203997e-16, -3.64550844e-17,  9.27947603e-17])

In [14]:
 X_train.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

# Step 5 : Model Building 

In [15]:
# train the decision tree
## Instantiate the model with 5 neighbors. 
model = KNeighborsClassifier(n_neighbors=5)
## Fit the model on the training data.
model.fit(X_train, y_train)

KNeighborsClassifier()

# Step 6 : Predictions on Train Dataset

In [16]:
X_train=pd.DataFrame(X_train,columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'])
X_train.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.571835 -0.281020       0.939998       1.368224  0.671036  0.865551   
1    -0.273098  0.093208       0.603282       0.799868  0.412964  0.186003   
2    -0.571835  0.249136       0.266567       0.357814  1.058144  0.186003   
3    -0.870571 -0.998289      -0.182388       0.168362  0.103277 -0.480477   
4    -0.870571 -1.310146       0.322686       0.610417 -0.705349  0.029184   

   DiabetesPedigreeFunction       Age  
0                 -0.683273 -0.461862  
1                 -0.504111 -0.630326  
2                  0.364369 -0.714558  
3                 -0.923168 -1.051486  
4                 -0.227777 -0.967254

In [17]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [18]:
y_train.reset_index(drop=True, inplace=True)

In [19]:
train=pd.concat([X_train,y_train],axis=1)
train.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.571835 -0.281020       0.939998       1.368224  0.671036  0.865551   
1    -0.273098  0.093208       0.603282       0.799868  0.412964  0.186003   
2    -0.571835  0.249136       0.266567       0.357814  1.058144  0.186003   
3    -0.870571 -0.998289      -0.182388       0.168362  0.103277 -0.480477   
4    -0.870571 -1.310146       0.322686       0.610417 -0.705349  0.029184   

   DiabetesPedigreeFunction       Age Outcome  
0                 -0.683273 -0.461862      No  
1                 -0.504111 -0.630326      No  
2                  0.364369 -0.714558      No  
3                 -0.923168 -1.051486      No  
4                 -0.227777 -0.967254      No

In [20]:
train['Predicted']=model.predict(X_train)
train.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.571835 -0.281020       0.939998       1.368224  0.671036  0.865551   
1    -0.273098  0.093208       0.603282       0.799868  0.412964  0.186003   
2    -0.571835  0.249136       0.266567       0.357814  1.058144  0.186003   
3    -0.870571 -0.998289      -0.182388       0.168362  0.103277 -0.480477   
4    -0.870571 -1.310146       0.322686       0.610417 -0.705349  0.029184   

   DiabetesPedigreeFunction       Age Outcome Predicted  
0                 -0.683273 -0.461862      No        No  
1                 -0.504111 -0.630326      No        No  
2                  0.364369 -0.714558      No        No  
3                 -0.923168 -1.051486      No        No  
4                 -0.227777 -0.967254      No        No

# Step 7 : Model Performance Metrics

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(train['Outcome'],train['Predicted'])
print(confusion_matrix)

[[310  41]
 [ 61 124]]


In [22]:
Accuracy_Train=((310+124)/(536)*100)
print(Accuracy_Train)

80.97014925373134


In [23]:
from sklearn.metrics import classification_report
print(classification_report(train['Outcome'], train['Predicted']))

              precision    recall  f1-score   support

          No       0.84      0.88      0.86       351
         Yes       0.75      0.67      0.71       185

    accuracy                           0.81       536
   macro avg       0.79      0.78      0.78       536
weighted avg       0.81      0.81      0.81       536



# Step 8 : Predictions on Test Dataset

In [24]:
X_test=pd.DataFrame(X_test,columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'])
X_test.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.870571  0.716921       0.715521       1.241923 -0.705349  1.244529   
1    -0.571835 -0.062720      -3.886261      -1.284102 -0.705349 -1.591276   
2    -0.571835 -0.842361      -0.070149      -0.147391 -0.051566 -0.754910   
3     0.324374  1.403005       0.154328      -0.084240  0.800072 -0.781046   
4     0.921846 -1.247775       0.491044       1.241923 -0.292434  1.950214   

   DiabetesPedigreeFunction       Age  
0                  0.412955 -0.461862  
1                  1.096200  3.244346  
2                  0.273270 -1.051486  
3                  0.352222  1.475474  
4                 -0.637723  0.717386

In [25]:
y_test.reset_index(drop=True, inplace=True)

In [26]:
test=pd.concat([X_test,y_test],axis=1)
test.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.870571  0.716921       0.715521       1.241923 -0.705349  1.244529   
1    -0.571835 -0.062720      -3.886261      -1.284102 -0.705349 -1.591276   
2    -0.571835 -0.842361      -0.070149      -0.147391 -0.051566 -0.754910   
3     0.324374  1.403005       0.154328      -0.084240  0.800072 -0.781046   
4     0.921846 -1.247775       0.491044       1.241923 -0.292434  1.950214   

   DiabetesPedigreeFunction       Age Outcome  
0                  0.412955 -0.461862      No  
1                  1.096200  3.244346      No  
2                  0.273270 -1.051486      No  
3                  0.352222  1.475474     Yes  
4                 -0.637723  0.717386      No

In [27]:
test['Predicted']=model.predict(X_test)
test.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.870571  0.716921       0.715521       1.241923 -0.705349  1.244529   
1    -0.571835 -0.062720      -3.886261      -1.284102 -0.705349 -1.591276   
2    -0.571835 -0.842361      -0.070149      -0.147391 -0.051566 -0.754910   
3     0.324374  1.403005       0.154328      -0.084240  0.800072 -0.781046   
4     0.921846 -1.247775       0.491044       1.241923 -0.292434  1.950214   

   DiabetesPedigreeFunction       Age Outcome Predicted  
0                  0.412955 -0.461862      No       Yes  
1                  1.096200  3.244346      No        No  
2                  0.273270 -1.051486      No        No  
3                  0.352222  1.475474     Yes       Yes  
4                 -0.637723  0.717386      No        No

# Step 9 : Model Performance Metrics on Test data 

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test['Outcome'],test['Predicted'])
print(confusion_matrix)

[[126  22]
 [ 39  44]]


In [29]:
Accuracy_test=((126+44)/(231)*100)
Accuracy_test

73.59307359307358

In [30]:
from sklearn.metrics import classification_report
print(classification_report(test['Outcome'], test['Predicted']))

              precision    recall  f1-score   support

          No       0.76      0.85      0.81       148
         Yes       0.67      0.53      0.59        83

    accuracy                           0.74       231
   macro avg       0.72      0.69      0.70       231
weighted avg       0.73      0.74      0.73       231



# Cross Validation Method  - Random concept

* To identify the best value of K

In [31]:
from sklearn.metrics import accuracy_score
for K in range(25):
    K_value = K+1
    model2 = KNeighborsClassifier(n_neighbors = K_value)
    model2.fit(X_train, y_train) 
    y_pred_Train= model2.predict(X_train)
    y_pred_test = model2.predict(X_test)
    print("Train Accuracy is ", 
          round(accuracy_score(y_train,y_pred_Train)*100,0), "      ","Test Accuracy is ", round(accuracy_score(y_test,y_pred_test)*100,0),"% for K-Value:",
          K_value)

Train Accuracy is  100.0        Test Accuracy is  68.0 % for K-Value: 1
Train Accuracy is  84.0        Test Accuracy is  71.0 % for K-Value: 2
Train Accuracy is  85.0        Test Accuracy is  74.0 % for K-Value: 3
Train Accuracy is  81.0        Test Accuracy is  74.0 % for K-Value: 4
Train Accuracy is  81.0        Test Accuracy is  74.0 % for K-Value: 5
Train Accuracy is  80.0        Test Accuracy is  72.0 % for K-Value: 6
Train Accuracy is  80.0        Test Accuracy is  76.0 % for K-Value: 7
Train Accuracy is  77.0        Test Accuracy is  73.0 % for K-Value: 8
Train Accuracy is  78.0        Test Accuracy is  76.0 % for K-Value: 9
Train Accuracy is  77.0        Test Accuracy is  74.0 % for K-Value: 10
Train Accuracy is  78.0        Test Accuracy is  75.0 % for K-Value: 11
Train Accuracy is  78.0        Test Accuracy is  74.0 % for K-Value: 12
Train Accuracy is  77.0        Test Accuracy is  77.0 % for K-Value: 13
Train Accuracy is  76.0        Test Accuracy is  75.0 % for K-Value: 14


# train the decision tree
## Instantiate the model with 5 neighbors. 
model = KNeighborsClassifier(n_neighbors=8,metric='euclidean')
## Fit the model on the training data.
model.fit(X_train, y_train)

In [35]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': np.arange(1, 26)}


knn2 = KNeighborsClassifier()
knn_gscv = GridSearchCV(knn2, 
                        param_grid, # 2,3,4,5,6,7,8
                        cv=10,
                        verbose=1)
knn_gscv.fit(X_train, y_train)

Fitting 10 folds for each of 25 candidates, totalling 250 fits


GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])},
             verbose=1)

In [33]:
#check top performing n_neighbors value
knn_gscv.best_params_

{'n_neighbors': 3}

In [34]:
knn_gscv.best_score_

0.7292802236198463

# Finish